development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: polyfriends_development
  pool: 5
  username: polyfriends

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: polyfriends_test
  pool: 5
  username: polyfriends
